import { degreesToRadians } from '../../../math/angles';
import { column, IDENTITY_MATRIX } from '../../../math/matrices';
import { rotationMatrixFromEuler } from '../../../math/rotations/euler';
import { geodesicDistanceDegrees } from '../../../math/rotations/geodesic';
import { gramSchmidt6D } from '../../../math/rotations/gramSchmidt';
import type { Matrix3,Vector3 } from '../../../math/types';
import type { SimulationContext,SimulationModule } from '../../../core/simulation/types';
import { createButton,createSlider,createToggle } from '../../../ui/controls/controls';
import { HeadPoseRenderer } from './HeadPoseRenderer';
const vector=(v:Vector3)=>`[${v.map(n=>n.toFixed(3)).join('  ')}]`;
const matrix=(m:Matrix3)=>`<span>R =</span><span class="matrix">${[0,1,2].map(r=>`<span>${m.slice(r*3,r*3+3).map(n=>n.toFixed(3)).join('   ')}</span>`).join('')}</span>`;
export class HeadPoseSimulation implements SimulationModule { readonly metadata={id:'head-pose-rotation',slug:'visual/head-pose',title:'Head Pose and 3D Rotation',modality:'visual' as const,topic:'Head Pose Estimation',description:'Explore yaw, pitch, roll and their rotation-matrix representation.'};private renderer:HeadPoseRenderer|null=null;private state={yaw:0,pitch:0,roll:0};private updateView:()=>void=()=>{};private resetControls:()=>void=()=>{};mount(context:SimulationContext):void{this.renderer=new HeadPoseRenderer(context.viewport);const math=document.createElement('div');math.className='math-grid';context.content.append(math);const sliders=(['yaw','pitch','roll'] as const).map(key=>createSlider({label:key[0].toUpperCase()+key.slice(1),min:key==='pitch'?-90:-180,max:key==='pitch'?90:180,step:1,value:0,unit:'°',onInput:value=>{this.state[key]=value;this.updateView();}}));sliders.forEach(s=>context.controls.append(s.element));context.controls.append(createToggle('Show local axes',true,value=>this.renderer?.setLocalAxesVisible(value)));context.controls.append(createButton('Reset orientation',()=>this.reset()));this.resetControls=()=>sliders.forEach(s=>s.setValue(0));this.updateView=()=>{const {yaw,pitch,roll}=this.state;const R=rotationMatrixFromEuler(degreesToRadians(yaw),degreesToRadians(pitch),degreesToRadians(roll));const a1=column(R,0),a2=column(R,1),reconstructed=gramSchmidt6D(a1,a2);this.renderer?.setRotation(R);math.innerHTML=`<section><h3>Euler representation</h3><p class="values">Yaw = ${yaw.toFixed(1)}°<br>Pitch = ${pitch.toFixed(1)}°<br>Roll = ${roll.toFixed(1)}°</p><small>Convention: R = Rz(roll) Ry(yaw) Rx(pitch)</small></section><section><h3>Original R</h3><div class="matrix-row">${matrix(R)}</div></section><section><h3>6D representation</h3><p class="mono">a₁ = ${vector(a1)}<br>a₂ = ${vector(a2)}<br>rotation6D = [a₁, a₂]</p><small>A 3D rotation has three physical degrees of freedom. The 6D representation is redundant and continuous for learning—not six independent rotations.</small></section><section><h3>Reconstructed from 6D</h3><div class="matrix-row">${matrix(reconstructed)}</div><p class="metric">Geodesic distance from neutral <strong>${geodesicDistanceDegrees(R,IDENTITY_MATRIX).toFixed(2)}°</strong></p></section>`;};this.updateView();context.animation.setUpdate(()=>this.renderer?.render());context.animation.start();}reset():void{this.state={yaw:0,pitch:0,roll:0};this.resetControls();this.updateView();}destroy():void{this.renderer?.destroy();this.renderer=null;}}
