import { SimulationRunner } from '../core/simulation/SimulationRunner';
import { simulationRegistry } from './simulationRegistry';

export class App {
  private readonly runner: SimulationRunner;
  constructor(private readonly root: HTMLElement) {
    root.innerHTML = `<header><a class="brand" href="#/visual/head-pose"><span class="mark">R</span><span>Rotation Lab<small>Mathematics & feature extraction</small></span></a><span class="topic">Head Pose Estimation</span></header><main><section class="workspace"><div class="visual"><div id="viewport"></div><div class="axis-key"><span class="x">X</span><span class="y">Y</span><span class="z">Z</span></div><a class="model-credit" href="https://creativecommons.org/licenses/by/3.0/" target="_blank" rel="noreferrer">Head scan: Lee Perry-Smith · CC BY 3.0</a></div><aside><p class="eyebrow">Interactive module · Visual</p><h1>Head Pose and<br>3D Rotation</h1><p class="lede">Rotate a head and inspect how Euler angles become an orthonormal basis in SO(3).</p><div id="controls"></div></aside></section><section id="content" class="content"></section><section class="explanation"><h2>What the representations tell us</h2><div><article><b>01</b><h3>Three degrees of freedom</h3><p>Yaw turns left–right, pitch nods up–down, and roll tilts sideways. Euler angles are intuitive, but have singularities and discontinuities.</p></article><article><b>02</b><h3>A rotation in SO(3)</h3><p>A valid matrix satisfies RᵀR = I and det(R) = 1. Its columns b₁, b₂, b₃ are the head’s rotated local axes.</p></article><article><b>03</b><h3>Learning with 6D</h3><p>A model can predict a₁ and a₂. Gram–Schmidt normalizes and orthogonalizes them, then b₃ = b₁ × b₂ completes the frame.</p></article><article><b>04</b><h3>Geodesic distance</h3><p>The distance is the smallest angular rotation connecting two orientations—not an element-by-element matrix difference.</p></article></div></section></main><footer>Interactive Mathematics & Feature Extraction Lab <span>Pure mathematics · modular simulations · reproducible learning</span></footer>`;
    const content = this.required('#content');
    if (document.body.classList.contains('embed')) this.required('aside').append(content);
    this.runner = new SimulationRunner(this.required('#viewport'), this.required('#controls'), content);
    window.addEventListener('hashchange', () => this.route());
    this.route();
  }
  private required(selector: string): HTMLElement { const element=this.root.querySelector<HTMLElement>(selector);if(!element)throw new Error(`Missing ${selector}`);return element; }
  private route(): void { const slug=location.hash.replace(/^#\/?/,'')||'visual/head-pose';const module=simulationRegistry.findBySlug(slug)??simulationRegistry.list()[0];if(module){document.body.dataset.simulation=module.metadata.id;const title=this.root.querySelector('h1'),topic=this.root.querySelector('.topic'),lede=this.root.querySelector('.lede'),explanation=this.root.querySelector<HTMLElement>('.explanation');if(title)title.textContent=module.metadata.title;if(topic)topic.textContent=module.metadata.topic;if(lede)lede.textContent=module.metadata.description;if(explanation)explanation.hidden=module.metadata.id!=='head-pose-rotation';this.runner.load(module);} }
}
